project_id = "lueodetbmvrcxeinxvxb"

[functions.validate-academic]
verify_jwt = false

[functions.moderate-text]
verify_jwt = false

[functions.moderate-image]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.get-turnstile-key]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
