-- Seed universities and their email domains from EMAIL_DOMAIN_MAP.
-- Step 1: Insert universities (skip if already present by name).
-- Step 2: Insert domain → university_id mappings (skip if domain already exists).
-- Safe to re-run (idempotent).

-- Step 1: Universities
INSERT INTO universities (id, name, created_at)
SELECT gen_random_uuid(), v.name, now()
FROM (VALUES
  ('İstanbul Üniversitesi'),
  ('İstanbul Teknik Üniversitesi'),
  ('Boğaziçi Üniversitesi'),
  ('Orta Doğu Teknik Üniversitesi'),
  ('Hacettepe Üniversitesi'),
  ('Ankara Üniversitesi'),
  ('Ege Üniversitesi'),
  ('Dokuz Eylül Üniversitesi'),
  ('Gazi Üniversitesi'),
  ('Marmara Üniversitesi'),
  ('Yıldız Teknik Üniversitesi'),
  ('Atatürk Üniversitesi'),
  ('Çukurova Üniversitesi'),
  ('Erciyes Üniversitesi'),
  ('Anadolu Üniversitesi'),
  ('Koç Üniversitesi'),
  ('Sabancı Üniversitesi'),
  ('Bilkent Üniversitesi'),
  ('Özyeğin Üniversitesi'),
  ('Bolu Abant İzzet Baysal Üniversitesi'),
  ('Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi'),
  ('Abdullah Gül Üniversitesi'),
  ('Adıyaman Üniversitesi'),
  ('Afyonkarahisar Sağlık Bilimleri Üniversitesi'),
  ('Afyon Kocatepe Üniversitesi'),
  ('Ağrı İbrahim Çeçen Üniversitesi'),
  ('Akdeniz Üniversitesi'),
  ('Aksaray Üniversitesi'),
  ('Alanya Alaaddin Keykubat Üniversitesi'),
  ('Amasya Üniversitesi'),
  ('Ankara Hacı Bayram Veli Üniversitesi'),
  ('Ankara Müzik ve Güzel Sanatlar Üniversitesi'),
  ('Ankara Sosyal Bilimler Üniversitesi'),
  ('Ankara Yıldırım Beyazıt Üniversitesi'),
  ('Ardahan Üniversitesi'),
  ('Artvin Çoruh Üniversitesi'),
  ('Aydın Adnan Menderes Üniversitesi'),
  ('Balıkesir Üniversitesi'),
  ('Bandırma Onyedi Eylül Üniversitesi'),
  ('Bartın Üniversitesi'),
  ('Batman Üniversitesi'),
  ('Bayburt Üniversitesi'),
  ('Bilecik Şeyh Edebali Üniversitesi'),
  ('Bingöl Üniversitesi'),
  ('Bitlis Eren Üniversitesi'),
  ('Burdur Mehmet Akif Ersoy Üniversitesi'),
  ('Bursa Teknik Üniversitesi'),
  ('Bursa Uludağ Üniversitesi'),
  ('Çanakkale Onsekiz Mart Üniversitesi'),
  ('Çankırı Karatekin Üniversitesi'),
  ('Dicle Üniversitesi'),
  ('Düzce Üniversitesi'),
  ('Erzincan Binali Yıldırım Üniversitesi'),
  ('Erzurum Teknik Üniversitesi'),
  ('Eskişehir Osmangazi Üniversitesi'),
  ('Eskişehir Teknik Üniversitesi'),
  ('Fırat Üniversitesi'),
  ('Galatasaray Üniversitesi'),
  ('Gaziantep Üniversitesi'),
  ('Gaziantep İslam Bilim ve Teknoloji Üniversitesi'),
  ('Tokat Gaziosmanpaşa Üniversitesi'),
  ('Gebze Teknik Üniversitesi'),
  ('Giresun Üniversitesi'),
  ('Gümüşhane Üniversitesi'),
  ('Hakkari Üniversitesi'),
  ('Harran Üniversitesi'),
  ('Hatay Mustafa Kemal Üniversitesi'),
  ('Hitit Üniversitesi'),
  ('Iğdır Üniversitesi'),
  ('İnönü Üniversitesi'),
  ('İskenderun Teknik Üniversitesi'),
  ('İstanbul Medeniyet Üniversitesi'),
  ('İstanbul Üniversitesi-Cerrahpaşa'),
  ('Isparta Uygulamalı Bilimler Üniversitesi'),
  ('İzmir Bakırçay Üniversitesi'),
  ('İzmir Demokrasi Üniversitesi'),
  ('İzmir Kâtip Çelebi Üniversitesi'),
  ('İzmir Yüksek Teknoloji Enstitüsü'),
  ('Kafkas Üniversitesi'),
  ('Kahramanmaraş İstiklal Üniversitesi'),
  ('Kahramanmaraş Sütçü İmam Üniversitesi'),
  ('Karabük Üniversitesi'),
  ('Karadeniz Teknik Üniversitesi'),
  ('Karamanoğlu Mehmetbey Üniversitesi'),
  ('Kastamonu Üniversitesi'),
  ('Kayseri Üniversitesi'),
  ('Kırıkkale Üniversitesi'),
  ('Kırklareli Üniversitesi'),
  ('Kırşehir Ahi Evran Üniversitesi'),
  ('Kilis 7 Aralık Üniversitesi'),
  ('Kocaeli Üniversitesi'),
  ('Konya Teknik Üniversitesi'),
  ('Kütahya Dumlupınar Üniversitesi'),
  ('Kütahya Sağlık Bilimleri Üniversitesi'),
  ('Malatya Turgut Özal Üniversitesi'),
  ('Manisa Celal Bayar Üniversitesi'),
  ('Mardin Artuklu Üniversitesi'),
  ('Mersin Üniversitesi'),
  ('Mimar Sinan Güzel Sanatlar Üniversitesi'),
  ('Muğla Sıtkı Koçman Üniversitesi'),
  ('Munzur Üniversitesi'),
  ('Muş Alparslan Üniversitesi'),
  ('Necmettin Erbakan Üniversitesi'),
  ('Nevşehir Hacı Bektaş Veli Üniversitesi'),
  ('Niğde Ömer Halisdemir Üniversitesi'),
  ('Ondokuz Mayıs Üniversitesi'),
  ('Ordu Üniversitesi'),
  ('Osmaniye Korkut Ata Üniversitesi'),
  ('Pamukkale Üniversitesi'),
  ('Recep Tayyip Erdoğan Üniversitesi'),
  ('Sağlık Bilimleri Üniversitesi'),
  ('Sakarya Üniversitesi'),
  ('Sakarya Uygulamalı Bilimler Üniversitesi'),
  ('Samsun Üniversitesi'),
  ('Selçuk Üniversitesi'),
  ('Siirt Üniversitesi'),
  ('Sinop Üniversitesi'),
  ('Sivas Cumhuriyet Üniversitesi'),
  ('Sivas Bilim ve Teknoloji Üniversitesi'),
  ('Süleyman Demirel Üniversitesi'),
  ('Şırnak Üniversitesi'),
  ('Tarsus Üniversitesi'),
  ('Tekirdağ Namık Kemal Üniversitesi'),
  ('Trakya Üniversitesi'),
  ('Trabzon Üniversitesi'),
  ('Uşak Üniversitesi'),
  ('Van Yüzüncü Yıl Üniversitesi'),
  ('Yalova Üniversitesi'),
  ('Yozgat Bozok Üniversitesi'),
  ('Zonguldak Bülent Ecevit Üniversitesi'),
  ('Acıbadem Üniversitesi'),
  ('Alanya Üniversitesi'),
  ('Altınbaş Üniversitesi'),
  ('Ankara Bilim Üniversitesi'),
  ('Ankara Medipol Üniversitesi'),
  ('Antalya Bilim Üniversitesi'),
  ('Antalya Belek Üniversitesi'),
  ('Atılım Üniversitesi'),
  ('Avrasya Üniversitesi'),
  ('Bahçeşehir Üniversitesi'),
  ('Başkent Üniversitesi'),
  ('Beykent Üniversitesi'),
  ('Beykoz Üniversitesi'),
  ('Bezmiâlem Vakıf Üniversitesi'),
  ('Biruni Üniversitesi'),
  ('Çağ Üniversitesi'),
  ('Çankaya Üniversitesi'),
  ('Demiroğlu Bilim Üniversitesi'),
  ('Doğuş Üniversitesi'),
  ('Fatih Sultan Mehmet Vakıf Üniversitesi'),
  ('Fenerbahçe Üniversitesi'),
  ('Haliç Üniversitesi'),
  ('Hasan Kalyoncu Üniversitesi'),
  ('İbn Haldun Üniversitesi'),
  ('Işık Üniversitesi'),
  ('İstanbul 29 Mayıs Üniversitesi'),
  ('İstanbul Arel Üniversitesi'),
  ('İstanbul Atlas Üniversitesi'),
  ('İstanbul Aydın Üniversitesi'),
  ('İstanbul Bilgi Üniversitesi'),
  ('İstanbul Esenyurt Üniversitesi'),
  ('İstanbul Galata Üniversitesi'),
  ('İstanbul Gedik Üniversitesi'),
  ('İstanbul Gelişim Üniversitesi'),
  ('İstanbul Kent Üniversitesi'),
  ('İstanbul Kültür Üniversitesi'),
  ('İstanbul Medipol Üniversitesi'),
  ('İstanbul Okan Üniversitesi'),
  ('İstanbul Rumeli Üniversitesi'),
  ('İstanbul Sabahattin Zaim Üniversitesi'),
  ('İstanbul Sağlık ve Teknoloji Üniversitesi'),
  ('İstanbul Ticaret Üniversitesi'),
  ('İstanbul Topkapı Üniversitesi'),
  ('İstanbul Yeni Yüzyıl Üniversitesi'),
  ('İstinye Üniversitesi'),
  ('İzmir Ekonomi Üniversitesi'),
  ('İzmir Tınaztepe Üniversitesi'),
  ('Kadir Has Üniversitesi'),
  ('Kapadokya Üniversitesi'),
  ('Kocaeli Sağlık ve Teknoloji Üniversitesi'),
  ('Konya Gıda ve Tarım Üniversitesi'),
  ('KTO Karatay Üniversitesi'),
  ('Lokman Hekim Üniversitesi'),
  ('Maltepe Üniversitesi'),
  ('MEF Üniversitesi'),
  ('Mudanya Üniversitesi'),
  ('Nişantaşı Üniversitesi'),
  ('Nuh Naci Yazgan Üniversitesi'),
  ('Ostim Teknik Üniversitesi'),
  ('Piri Reis Üniversitesi'),
  ('Sanko Üniversitesi'),
  ('TED Üniversitesi'),
  ('TOBB Ekonomi ve Teknoloji Üniversitesi'),
  ('Toros Üniversitesi'),
  ('Türk-Alman Üniversitesi'),
  ('Türk Hava Kurumu Üniversitesi'),
  ('Ufuk Üniversitesi'),
  ('Üsküdar Üniversitesi'),
  ('Yaşar Üniversitesi'),
  ('Yeditepe Üniversitesi'),
  ('Yüksek İhtisas Üniversitesi')
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM universities u WHERE u.name = v.name);

-- Step 2: Domain mappings
-- ODTÜ has two domains (metu + odtu), İTÜ has a mail. subdomain in existing data — only primary domains here.
INSERT INTO university_email_domains (id, university_id, domain, is_primary, is_verified, created_at)
SELECT gen_random_uuid(), u.id, v.domain, true, true, now()
FROM (VALUES
  ('istanbul.edu.tr',      'İstanbul Üniversitesi'),
  ('itu.edu.tr',           'İstanbul Teknik Üniversitesi'),
  ('boun.edu.tr',          'Boğaziçi Üniversitesi'),
  ('metu.edu.tr',          'Orta Doğu Teknik Üniversitesi'),
  ('odtu.edu.tr',          'Orta Doğu Teknik Üniversitesi'),
  ('hacettepe.edu.tr',     'Hacettepe Üniversitesi'),
  ('ankara.edu.tr',        'Ankara Üniversitesi'),
  ('ege.edu.tr',           'Ege Üniversitesi'),
  ('deu.edu.tr',           'Dokuz Eylül Üniversitesi'),
  ('gazi.edu.tr',          'Gazi Üniversitesi'),
  ('marmara.edu.tr',       'Marmara Üniversitesi'),
  ('yildiz.edu.tr',        'Yıldız Teknik Üniversitesi'),
  ('atauni.edu.tr',        'Atatürk Üniversitesi'),
  ('cu.edu.tr',            'Çukurova Üniversitesi'),
  ('erciyes.edu.tr',       'Erciyes Üniversitesi'),
  ('anadolu.edu.tr',       'Anadolu Üniversitesi'),
  ('ku.edu.tr',            'Koç Üniversitesi'),
  ('sabanciuniv.edu',      'Sabancı Üniversitesi'),
  ('bilkent.edu.tr',       'Bilkent Üniversitesi'),
  ('ozyegin.edu.tr',       'Özyeğin Üniversitesi'),
  ('ibu.edu.tr',           'Bolu Abant İzzet Baysal Üniversitesi'),
  ('atu.edu.tr',           'Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi'),
  ('agu.edu.tr',           'Abdullah Gül Üniversitesi'),
  ('adiyaman.edu.tr',      'Adıyaman Üniversitesi'),
  ('afsu.edu.tr',          'Afyonkarahisar Sağlık Bilimleri Üniversitesi'),
  ('aku.edu.tr',           'Afyon Kocatepe Üniversitesi'),
  ('agri.edu.tr',          'Ağrı İbrahim Çeçen Üniversitesi'),
  ('akdeniz.edu.tr',       'Akdeniz Üniversitesi'),
  ('aksaray.edu.tr',       'Aksaray Üniversitesi'),
  ('alanya.edu.tr',        'Alanya Alaaddin Keykubat Üniversitesi'),
  ('amasya.edu.tr',        'Amasya Üniversitesi'),
  ('ahbv.edu.tr',          'Ankara Hacı Bayram Veli Üniversitesi'),
  ('mgu.edu.tr',           'Ankara Müzik ve Güzel Sanatlar Üniversitesi'),
  ('asbu.edu.tr',          'Ankara Sosyal Bilimler Üniversitesi'),
  ('aybu.edu.tr',          'Ankara Yıldırım Beyazıt Üniversitesi'),
  ('ardahan.edu.tr',       'Ardahan Üniversitesi'),
  ('artvin.edu.tr',        'Artvin Çoruh Üniversitesi'),
  ('adu.edu.tr',           'Aydın Adnan Menderes Üniversitesi'),
  ('balikesir.edu.tr',     'Balıkesir Üniversitesi'),
  ('bandirma.edu.tr',      'Bandırma Onyedi Eylül Üniversitesi'),
  ('bartin.edu.tr',        'Bartın Üniversitesi'),
  ('batman.edu.tr',        'Batman Üniversitesi'),
  ('bayburt.edu.tr',       'Bayburt Üniversitesi'),
  ('bilecik.edu.tr',       'Bilecik Şeyh Edebali Üniversitesi'),
  ('bingol.edu.tr',        'Bingöl Üniversitesi'),
  ('beu.edu.tr',           'Bitlis Eren Üniversitesi'),
  ('mehmetakif.edu.tr',    'Burdur Mehmet Akif Ersoy Üniversitesi'),
  ('btu.edu.tr',           'Bursa Teknik Üniversitesi'),
  ('uludag.edu.tr',        'Bursa Uludağ Üniversitesi'),
  ('comu.edu.tr',          'Çanakkale Onsekiz Mart Üniversitesi'),
  ('karatekin.edu.tr',     'Çankırı Karatekin Üniversitesi'),
  ('dicle.edu.tr',         'Dicle Üniversitesi'),
  ('duzce.edu.tr',         'Düzce Üniversitesi'),
  ('erzincan.edu.tr',      'Erzincan Binali Yıldırım Üniversitesi'),
  ('erzurum.edu.tr',       'Erzurum Teknik Üniversitesi'),
  ('ogu.edu.tr',           'Eskişehir Osmangazi Üniversitesi'),
  ('eskisehir.edu.tr',     'Eskişehir Teknik Üniversitesi'),
  ('firat.edu.tr',         'Fırat Üniversitesi'),
  ('gsu.edu.tr',           'Galatasaray Üniversitesi'),
  ('gantep.edu.tr',        'Gaziantep Üniversitesi'),
  ('gibtu.edu.tr',         'Gaziantep İslam Bilim ve Teknoloji Üniversitesi'),
  ('gop.edu.tr',           'Tokat Gaziosmanpaşa Üniversitesi'),
  ('gtu.edu.tr',           'Gebze Teknik Üniversitesi'),
  ('giresun.edu.tr',       'Giresun Üniversitesi'),
  ('gumushane.edu.tr',     'Gümüşhane Üniversitesi'),
  ('hakkari.edu.tr',       'Hakkari Üniversitesi'),
  ('harran.edu.tr',        'Harran Üniversitesi'),
  ('mku.edu.tr',           'Hatay Mustafa Kemal Üniversitesi'),
  ('hitit.edu.tr',         'Hitit Üniversitesi'),
  ('igdir.edu.tr',         'Iğdır Üniversitesi'),
  ('inonu.edu.tr',         'İnönü Üniversitesi'),
  ('iste.edu.tr',          'İskenderun Teknik Üniversitesi'),
  ('medeniyet.edu.tr',     'İstanbul Medeniyet Üniversitesi'),
  ('iuc.edu.tr',           'İstanbul Üniversitesi-Cerrahpaşa'),
  ('isubyu.edu.tr',        'Isparta Uygulamalı Bilimler Üniversitesi'),
  ('bakircay.edu.tr',      'İzmir Bakırçay Üniversitesi'),
  ('idu.edu.tr',           'İzmir Demokrasi Üniversitesi'),
  ('ikcu.edu.tr',          'İzmir Kâtip Çelebi Üniversitesi'),
  ('iyte.edu.tr',          'İzmir Yüksek Teknoloji Enstitüsü'),
  ('kafkas.edu.tr',        'Kafkas Üniversitesi'),
  ('istiklal.edu.tr',      'Kahramanmaraş İstiklal Üniversitesi'),
  ('ksu.edu.tr',           'Kahramanmaraş Sütçü İmam Üniversitesi'),
  ('karabuk.edu.tr',       'Karabük Üniversitesi'),
  ('ktu.edu.tr',           'Karadeniz Teknik Üniversitesi'),
  ('kmu.edu.tr',           'Karamanoğlu Mehmetbey Üniversitesi'),
  ('kastamonu.edu.tr',     'Kastamonu Üniversitesi'),
  ('kayseri.edu.tr',       'Kayseri Üniversitesi'),
  ('kku.edu.tr',           'Kırıkkale Üniversitesi'),
  ('klu.edu.tr',           'Kırklareli Üniversitesi'),
  ('ahievran.edu.tr',      'Kırşehir Ahi Evran Üniversitesi'),
  ('kilis.edu.tr',         'Kilis 7 Aralık Üniversitesi'),
  ('kocaeli.edu.tr',       'Kocaeli Üniversitesi'),
  ('ktun.edu.tr',          'Konya Teknik Üniversitesi'),
  ('dpu.edu.tr',           'Kütahya Dumlupınar Üniversitesi'),
  ('ksbu.edu.tr',          'Kütahya Sağlık Bilimleri Üniversitesi'),
  ('ozal.edu.tr',          'Malatya Turgut Özal Üniversitesi'),
  ('cbu.edu.tr',           'Manisa Celal Bayar Üniversitesi'),
  ('artuklu.edu.tr',       'Mardin Artuklu Üniversitesi'),
  ('mersin.edu.tr',        'Mersin Üniversitesi'),
  ('msgsu.edu.tr',         'Mimar Sinan Güzel Sanatlar Üniversitesi'),
  ('mu.edu.tr',            'Muğla Sıtkı Koçman Üniversitesi'),
  ('munzur.edu.tr',        'Munzur Üniversitesi'),
  ('alparslan.edu.tr',     'Muş Alparslan Üniversitesi'),
  ('erbakan.edu.tr',       'Necmettin Erbakan Üniversitesi'),
  ('nevsehir.edu.tr',      'Nevşehir Hacı Bektaş Veli Üniversitesi'),
  ('ohu.edu.tr',           'Niğde Ömer Halisdemir Üniversitesi'),
  ('omu.edu.tr',           'Ondokuz Mayıs Üniversitesi'),
  ('odu.edu.tr',           'Ordu Üniversitesi'),
  ('osmaniye.edu.tr',      'Osmaniye Korkut Ata Üniversitesi'),
  ('pau.edu.tr',           'Pamukkale Üniversitesi'),
  ('erdogan.edu.tr',       'Recep Tayyip Erdoğan Üniversitesi'),
  ('sbu.edu.tr',           'Sağlık Bilimleri Üniversitesi'),
  ('sakarya.edu.tr',       'Sakarya Üniversitesi'),
  ('subu.edu.tr',          'Sakarya Uygulamalı Bilimler Üniversitesi'),
  ('samsun.edu.tr',        'Samsun Üniversitesi'),
  ('selcuk.edu.tr',        'Selçuk Üniversitesi'),
  ('siirt.edu.tr',         'Siirt Üniversitesi'),
  ('sinop.edu.tr',         'Sinop Üniversitesi'),
  ('cumhuriyet.edu.tr',    'Sivas Cumhuriyet Üniversitesi'),
  ('sivas.edu.tr',         'Sivas Bilim ve Teknoloji Üniversitesi'),
  ('sdu.edu.tr',           'Süleyman Demirel Üniversitesi'),
  ('sirnak.edu.tr',        'Şırnak Üniversitesi'),
  ('tarsus.edu.tr',        'Tarsus Üniversitesi'),
  ('nku.edu.tr',           'Tekirdağ Namık Kemal Üniversitesi'),
  ('trakya.edu.tr',        'Trakya Üniversitesi'),
  ('trabzon.edu.tr',       'Trabzon Üniversitesi'),
  ('usak.edu.tr',          'Uşak Üniversitesi'),
  ('yyu.edu.tr',           'Van Yüzüncü Yıl Üniversitesi'),
  ('yalova.edu.tr',        'Yalova Üniversitesi'),
  ('bozok.edu.tr',         'Yozgat Bozok Üniversitesi'),
  ('beun.edu.tr',          'Zonguldak Bülent Ecevit Üniversitesi'),
  ('acibadem.edu.tr',      'Acıbadem Üniversitesi'),
  ('alanyau.edu.tr',       'Alanya Üniversitesi'),
  ('altinbas.edu.tr',      'Altınbaş Üniversitesi'),
  ('ankarabilim.edu.tr',   'Ankara Bilim Üniversitesi'),
  ('ankaramedipol.edu.tr', 'Ankara Medipol Üniversitesi'),
  ('antalya.edu.tr',       'Antalya Bilim Üniversitesi'),
  ('belek.edu.tr',         'Antalya Belek Üniversitesi'),
  ('atilim.edu.tr',        'Atılım Üniversitesi'),
  ('avrasya.edu.tr',       'Avrasya Üniversitesi'),
  ('bau.edu.tr',           'Bahçeşehir Üniversitesi'),
  ('baskent.edu.tr',       'Başkent Üniversitesi'),
  ('beykent.edu.tr',       'Beykent Üniversitesi'),
  ('beykoz.edu.tr',        'Beykoz Üniversitesi'),
  ('bezmialem.edu.tr',     'Bezmiâlem Vakıf Üniversitesi'),
  ('biruni.edu.tr',        'Biruni Üniversitesi'),
  ('cag.edu.tr',           'Çağ Üniversitesi'),
  ('cankaya.edu.tr',       'Çankaya Üniversitesi'),
  ('demiroglu.edu.tr',     'Demiroğlu Bilim Üniversitesi'),
  ('dogus.edu.tr',         'Doğuş Üniversitesi'),
  ('fsm.edu.tr',           'Fatih Sultan Mehmet Vakıf Üniversitesi'),
  ('fbu.edu.tr',           'Fenerbahçe Üniversitesi'),
  ('halic.edu.tr',         'Haliç Üniversitesi'),
  ('hku.edu.tr',           'Hasan Kalyoncu Üniversitesi'),
  ('ibnhaldun.edu.tr',     'İbn Haldun Üniversitesi'),
  ('isikun.edu.tr',        'Işık Üniversitesi'),
  ('29mayis.edu.tr',       'İstanbul 29 Mayıs Üniversitesi'),
  ('arel.edu.tr',          'İstanbul Arel Üniversitesi'),
  ('atlas.edu.tr',         'İstanbul Atlas Üniversitesi'),
  ('aydin.edu.tr',         'İstanbul Aydın Üniversitesi'),
  ('bilgi.edu.tr',         'İstanbul Bilgi Üniversitesi'),
  ('esenyurt.edu.tr',      'İstanbul Esenyurt Üniversitesi'),
  ('galata.edu.tr',        'İstanbul Galata Üniversitesi'),
  ('gedik.edu.tr',         'İstanbul Gedik Üniversitesi'),
  ('gelisim.edu.tr',       'İstanbul Gelişim Üniversitesi'),
  ('kent.edu.tr',          'İstanbul Kent Üniversitesi'),
  ('iku.edu.tr',           'İstanbul Kültür Üniversitesi'),
  ('medipol.edu.tr',       'İstanbul Medipol Üniversitesi'),
  ('okan.edu.tr',          'İstanbul Okan Üniversitesi'),
  ('rumeli.edu.tr',        'İstanbul Rumeli Üniversitesi'),
  ('izu.edu.tr',           'İstanbul Sabahattin Zaim Üniversitesi'),
  ('istun.edu.tr',         'İstanbul Sağlık ve Teknoloji Üniversitesi'),
  ('ticaret.edu.tr',       'İstanbul Ticaret Üniversitesi'),
  ('topkapi.edu.tr',       'İstanbul Topkapı Üniversitesi'),
  ('yeniyuzyil.edu.tr',    'İstanbul Yeni Yüzyıl Üniversitesi'),
  ('istinye.edu.tr',       'İstinye Üniversitesi'),
  ('ieu.edu.tr',           'İzmir Ekonomi Üniversitesi'),
  ('tinaztepe.edu.tr',     'İzmir Tınaztepe Üniversitesi'),
  ('khas.edu.tr',          'Kadir Has Üniversitesi'),
  ('kapadokya.edu.tr',     'Kapadokya Üniversitesi'),
  ('kstu.edu.tr',          'Kocaeli Sağlık ve Teknoloji Üniversitesi'),
  ('gidatarim.edu.tr',     'Konya Gıda ve Tarım Üniversitesi'),
  ('karatay.edu.tr',       'KTO Karatay Üniversitesi'),
  ('lokmanhekim.edu.tr',   'Lokman Hekim Üniversitesi'),
  ('maltepe.edu.tr',       'Maltepe Üniversitesi'),
  ('mef.edu.tr',           'MEF Üniversitesi'),
  ('mudanya.edu.tr',       'Mudanya Üniversitesi'),
  ('nisantasi.edu.tr',     'Nişantaşı Üniversitesi'),
  ('nny.edu.tr',           'Nuh Naci Yazgan Üniversitesi'),
  ('ostimteknik.edu.tr',   'Ostim Teknik Üniversitesi'),
  ('pirireis.edu.tr',      'Piri Reis Üniversitesi'),
  ('sanko.edu.tr',         'Sanko Üniversitesi'),
  ('tedu.edu.tr',          'TED Üniversitesi'),
  ('etu.edu.tr',           'TOBB Ekonomi ve Teknoloji Üniversitesi'),
  ('toros.edu.tr',         'Toros Üniversitesi'),
  ('tau.edu.tr',           'Türk-Alman Üniversitesi'),
  ('thk.edu.tr',           'Türk Hava Kurumu Üniversitesi'),
  ('ufuk.edu.tr',          'Ufuk Üniversitesi'),
  ('uskudar.edu.tr',       'Üsküdar Üniversitesi'),
  ('yasar.edu.tr',         'Yaşar Üniversitesi'),
  ('yeditepe.edu.tr',      'Yeditepe Üniversitesi'),
  ('yiu.edu.tr',           'Yüksek İhtisas Üniversitesi')
) AS v(domain, university_name)
JOIN universities u ON u.name = v.university_name
WHERE NOT EXISTS (
  SELECT 1 FROM university_email_domains ued WHERE ued.domain = v.domain
);
